// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using UploadExcelFileTask.Models;

namespace UploadExcelFileTask.Data
{
    public partial class AAISContext : DbContext
    {
        public AAISContext()
        {
        }

        public AAISContext(DbContextOptions<AAISContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AAISDetail> AAISDetails { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {

                optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=AAIS;Integrated Security=True;Trusted_Connection=True;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AAISDetail>(entity =>
            {
                entity.HasKey(e => e.WO_Number)
                    .HasName("PK__Details__9CD6C177AA041CEB");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}