// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UploadExcelFileTask.Models
{
    [Table("AAISDetail")]
    public partial class AAISDetail
    {
        [Key]
        public int WO_Number { get; set; }
        public string Description { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Location { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Status { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Type { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Priority { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Scheduled_FinishDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Completion_Date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string State { get; set; }
        public string Reason { get; set; }
    }
}